Bug #50648 UDM CLI: list --policies
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 1104, in <module>
    print('\n'.join(doit(sys.argv)))
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 396, in doit
    out = _doit(arglist)
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 672, in _doit
    out.extend(cli.list(list_policies, filter, superordinate_dn, policyOptions, policies_with_DN))
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 704, in list
    return self._list(self.module_name, self.module, self.dn, self.lo, self.position, self.superordinate, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 999, in _list
    policyResults = p1.communicate()[0].split('\n')
TypeError: a bytes-like object is required, not 'str'